apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcommerce-commerce
  namespace: bcommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bcommerce-commerce
  template:
    metadata:
      labels:
        app: bcommerce-commerce
    spec:
      containers:
        - name: commerce
          image: bcommerce/commerce:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 20
          resources:
            requests:
              memory: "768Mi"
              cpu: "300m"
            limits:
              memory: "1536Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: bcommerce-commerce
  namespace: bcommerce
spec:
  selector:
    app: bcommerce-commerce
  ports:
    - port: 8081
      targetPort: 8081
